# Generated by Django 4.2.10 on 2024-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, max_length=256)),
                ("id_bigint", models.BigIntegerField(default=0)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=3),
                ),
                ("published_date", models.DateField(default="1970-01-01")),
                ("is_published", models.BooleanField(default=True)),
                ("cover", models.FileField(blank=True, upload_to="cover/")),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="cover/images/"),
                ),
            ],
        ),
    ]
