# Generated by Django 4.2.10 on 2024-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0003_characters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                (
                    "book",
                    models.ManyToManyField(related_name="authors", to="demo.book"),
                ),
            ],
        ),
    ]
